version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - "/srv/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/srv/docker/mosquitto/data:/mosquitto/data"
      - "/srv/docker/mosquitto/log:/mosquitto/log"
