gateway:
  mqtt:
    broker-url: tcp://iot.emmet-project.com:1883
#    broker-url: tcp://iot.eclipse.org:1883
#    broker-url: tcp://61.62.58.30:5566


spring:
  rabbitmq:
    host: iot.emmet-project.com
    port: 5672
    virtual-host: /
    username: emmet
    password: masterbuilder
 

logging.level.com.emmet: DEBUG